--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name:              Date-Gregorian
version:           0.10
author:
  - Martin Becker <hasch-cpan-dg@cozap.com>
license:           perl
distribution_type: module
abstract:          Gregorian calendar
dynamic_config:    0
requires:
recommends:
  DateTime: 0.1501
build_requires:
generated_by:      Martin Becker
