--- YAML:1.0

name:              Date-Gregorian
version:           0.07
version_from:      lib/Date/Gregorian.pm
license:           perl
distribution_type: module
installdirs:       site
dynamic_config:    0
requires:

build_requires:

