---
name:              Date-Gregorian
version:           0.08
version_from:      lib/Date/Gregorian.pm
license:           perl
distribution_type: module
installdirs:       site
dynamic_config:    0
requires:
build_requires:
